server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ozmenab/eventhub-config
          default-label: dev
          clone-on-start: true
          search-paths:
            - "{application}"

management:
  endpoints:
    web:
      exposure:
        include: health,info
